name: Deploy Staging
on:
  push:
    branches:
      -staging
  workflow_dispatch:
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'TODO: TEST APP FIRST'
        run: echo SMOKE TEST BUILD AND TESTS GO HERE
        
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Get current date (backup directory naming)
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d@%H:%M:%S')"
        
      - name: Execute Remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOYMENT_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Create a directory for a backup
            mkdir /var/www/backups/${{ steps.date.outputs.date }}
            
            # Copy the staging directory to the backup
            cp -r /var/www/staging-late-stage /var/www/backups/${{ steps.date.outputs.date }}/staging-late-stage
            
            # Remove the node_modules from the backups to conserve space
            cd /var/www/backups/${{ steps.date.outputs.date }}/staging-late-stage
            rm -rf node_modules
            rm -rf apps/api/node_modules
            rm -rf apps/client/node_modules
            
            # Print the backups directory, so we know when it's time to clean out old ones
            ls /var/www/backups
            
            # Deploy
            cd /var/www/staging-late-state
            git checkout staging
            git stash
            git pull origin staging
            pnpm migrate:deploy
            pnpm generate
            pnpm build
            pnpm start
