name: Deploy Staging
on:
  push:
    branches:
      -staging
  workflow_dispatch:
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'TODO: TEST APP FIRST'
        run: echo SMOKE TEST BUILD AND TESTS GO HERE
        
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Get current date (backup directory naming)
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d@%H:%M:%S')"
        
      - name: Execute Remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOYMENT_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            ls -a
            sudo mkdir /var/backup/${{ steps.date.outputs.date }}
            
    
#       - name: Install SSH
#         uses: shimataro/ssh-key-action@v2
#         with:
#           key: ${{ secrets.DEPLOYMENT_KEY }} 
#           known_hosts: 'PLACEHOLDER FOR NEXT STEP'
        
#       - name: Keyscan Server And Add Known Hosts
#         run: ssh-keyscan -H ${{ secrets.DEPLOYMENT_HOST }} >> ~/.ssh/known_hosts
        
#       - name: Print Runner SSH Dir
#         run: |
#           ls -a /home/runner/.ssh
#           echo ${{ secrets.SSH_USER }}
#           echo ${{ secrets.DEPLOYMENT_HOST }}
          


#       - name: Deploy Script
#         run: |
#           # Remote into the server
#           ssh ${{ secrets.SSH_USER }}@${{ secrets.DEPLOYMENT_HOST }} -i /home/runner/.ssh/id_rsa
          
#           ls -a
                    
          

          
