name: Deploy Staging
on:
  push:
    branches:
      -staging
  workflow_dispatch:
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'TODO: TEST APP FIRST'
        run: echo SMOKE TEST BUILD AND TESTS GO HERE
        
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
    
      - name: Install SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOYMENT_KEY }} 
          known_hosts: 'PLACEHOLDER FOR NEXT STEP'
        
      - name: Keyscan Server And Add Known Hosts
        run: ssh-keyscan -H ${{ secrets.DEPLOYMENT_HOST }} >> ~/.ssh/known_hosts
        
      - name: Print Runner SSH Dir
        run: |
          ls -a /home/runner/.ssh
          echo ${{ secrets.SSH_USER }}
          echo ${{ secrets.DEPLOYMENT_HOST }}
        
      - name: Remote deployment script
        env:
          BACKUP_DIRNAME: $(echo $(date -I))
          
        run: |
          # Remote into the server
          ssh ${{ secrets.SSH_USER }}@${{ secrets.DEPLOYMENT_HOST }} -i /home/runner/.ssh/id_rsa
          
          echo "NOW::$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
          
          # Make a backup file for the previous build
          sudo mkdir /var/backup/$(NOW)
          
          # Copy the contents of the build to the backup directory from the last step
          
