name: Deploy Staging
on:
  push:
    branches:
      -staging
  workflow_dispatch:
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'TODO: TEST APP FIRST'
        run: echo SMOKE TEST BUILD AND TESTS GO HERE
        
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
    
      - name: Install SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOYMENT_KEY }} 
          known_hosts: 'PLACEHOLDER FOR NEXT STEP'
        
      - name: Add Known Hosts
        run: ssh-keyscan -H ${{ secrets.DEPLOYMENT_HOST }} >> ~/.ssh/known_hosts
        
      - name: Print Runner SSH Dir
        run: |
          ls -a /home/runner/.ssh
          echo ${{ secrets.SSH_USER }}
          echo ${{ secrets.DEPLOYMENT_HOST }}
        
      - name: Remote deployment script
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.DEPLOYMENT_HOST }}
      
