name: Dev Branch PR
on:
  workflow_call:
    secrets:
      DEV_DATABASE_URL:
        required: true
      DEV_API_KEY:
        required: true
      DEV_TOKEN_SECRET:
        required: true
      DEV_COOKIE_SECRET:
        required: true
      DEV_SENDGRID_API_KEY:
        required: true
      DEV_VITE_SVELTEKIT_HOST:
        required: true
      DEV_VITE_HOST_ADDRESS:
        required: true
      DEV_API_HOST:
        required: true
      DEV_API_PATH:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] # 16.13.2
    environment: dev

    steps:
      - uses: actions/checkout@v2
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true

      - name: Create api .env file
        run: |
          cd apps/api
          touch .env

          echo DATABASE_URL=${{ secrets.DEV_DATABASE_URL }} >> .env
          echo CORS_ORIGIN=https://ls.localhost >> .env
          echo API_KEY=${{ secrets.DEV_API_KEY }} >> .env
          echo TOKEN_SECRET=${{ secrets.DEV_TOKEN_SECRET }} >> .env
          echo COOKIE_SECRET=${{ secrets.DEV_COOKIE_SECRET }} >> .env
          echo NODE_ENV=test >> .env
          echo SENDGRID_API_KEY=${{ secrets.DEV_SENDGRID_API_KEY }} >> .env
          echo PORT=3001 >> .env

          cat .env
          cd ../../
          
      - name: Create client .env file
        run: |
          ls -la
          cd apps/client
          touch .env
          
          echo VITE_SVELTEKIT_HOST=${{ secrets.DEV_VITE_SVELTEKIT_HOST }} >> .env
          echo VITE_HOST_ADDRESS=${{ secrets.DEV_VITE_HOST_ADDRESS }} >> .env
          echo API_KEY=${{ secrets.DEV_API_KEY }} >> .env
          echo API_HOST=${{ secrets.DEV_API_HOST }} >> .env
          echo API_PATH=${{ secrets.DEV_API_PATH }} >> .env
          echo NODE_ENV=test >> .env
          echo PORT=3000 >> .env
          
          cat .env
          cd ../../

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
        env:
          DATABASE_URL: $DATABASE_URL

      - run: pnpm migrate:deploy
      - run: pnpm generate
      - run: pnpm test:ci
      - run: pnpm build
