name: Dev Branch PR
on:
  workflow_call:
    secrets:
      DATABASE_URL:
        required: true
      STAGING_DATABASE_URL:
        required: true
      DATABASE_USER:
        required: true
      DATABASE_PASSWORD:
        required: true
      DATABASE_HOST:
        required: true
      DATABASE_PORT:
        required: true
      DATABASE_NAME:
        required: true
      STAGING_DATABASE_USER:
        required: true
      STAGING_DATABASE_PASSWORD:
        required: true
      STAGING_DATABASE_HOST:
        required: true
      STAGING_DATABASE_PORT:
        required: true
      STAGING_DATABASE_NAME:
        required: true
      API_KEY:
        required: true
      TOKEN_SECRET:
        required: true
      COOKIE_SECRET:
        required: true
      SENDGRID_API_KEY:
        required: true
      VITE_SVELTEKIT_HOST:
        required: true
      VITE_HOST_ADDRESS:
        required: true
      API_HOST:
        required: true
      API_PATH:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] # 16.13.2
    environment: dev

    steps:
      - uses: actions/checkout@v2
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: false

      - name: Create api .env file
        run: |
          cd apps/api
          touch .env

          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo CORS_ORIGIN=https://ls.localhost >> .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
          echo TOKEN_SECRET=${{ secrets.TOKEN_SECRET }} >> .env
          echo COOKIE_SECRET=${{ secrets.COOKIE_SECRET }} >> .env
          echo NODE_ENV=test >> .env
          echo SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }} >> .env
          echo PORT=3001 >> .env

          cat .env
          cd ../../

      - name: Create client .env file
        run: |
          ls -la
          cd apps/client
          touch .env

          echo VITE_SVELTEKIT_HOST=${{ secrets.VITE_SVELTEKIT_HOST }} >> .env
          echo VITE_HOST_ADDRESS=${{ secrets.VITE_HOST_ADDRESS }} >> .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
          echo API_HOST=${{ secrets.API_HOST }} >> .env
          echo API_PATH=${{ secrets.API_PATH }} >> .env
          echo NODE_ENV=test >> .env
          echo PORT=3000 >> .env

          cat .env
          cd ../../

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
        env:
          DATABASE_URL: $DATABASE_URL

      # Install
      - run: pnpm install --no-frozen-lockfile

      # Reset & Restore Dev DB
      - run: pnpm branch -- --force

      # Run new migrations
      - run: pnpm migrate:deploy

      # Generate TS
      - run: pnpm generate

      # Tests
      - run: pnpm test:ci

      # Build smoke-test
      - run: pnpm build
