name: Dev Branch PR
on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] # 16.13.2

    steps:
      - name: Create api env file
        run: |
          cd apps/api
          touch .env
          
          echo DATABASE_URL=${{ secrets.DEV_DATABASE_URL }} >> .env
          echo CORS_ORIGIN=https://ls.localhost >> .env
          echo API_KEY=${{ secrets.DEV_API_KEY }} >> .env
          echo TOKEN_SECRET=${{ secrets.DEV_TOKEN_SECRET }} >> .env
          echo COOKIE_SECRET=${{ secrets.DEV_COOKIE_SECRET }} >> .env
          echo NODE_ENV=test >> .env
          echo SENDGRID_API_KEY=${{ secrets.DEV_SENDGRID_API_KEY }} >> .env
          echo PORT=3001 >> .env
          
          cat .env
          cd ../../
          
          
      - uses: actions/checkout@v2
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
        env:
          DATABASE_URL: $DATABASE_URL
      - run: pnpm migrate
      - run: pnpm test
      - run: pnpm build
