name: PR
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - staging
  workflow_dispatch:
  
jobs:
  check-if-dev-branch:
    if: github.ref == 'refs/heads/dev' || github.event.pull_request.base.ref == 'dev'
    uses: jeffDevelops/late-stage/.github/workflows/DevPR.yml@dev # <- TODO: Change branch to main
    secrets:
      DEV_DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
      DEV_API_KEY: ${{ secrets.DEV_API_KEY }}
      DEV_COOKIE_SECRET: ${{ secrets.DEV_COOKIE_SECRET }}
      DEV_TOKEN_SECRET: ${{ secrets.DEV_TOKEN_SECRET }}
      DEV_SENDGRID_API_KEY: ${{ secrets.DEV_SENDGRID_API_KEY }}
        
  check-if-staging-branch:
    if: github.event.pull_request.base.ref == 'staging'
    runs-on: ubuntu-latest
    steps:
      - name: Check if pull request -> staging
        run: echo "Running staging branch PR workflow"
      
  check-if-main-branch:    
    if: github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Check if pull request -> main
        run: echo "Running main branch PR workflow"
