name: Dev Branch PR
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - staging

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
        
      - name: Check if pull request -> dev
        if: github.ref == 'refs/heads/dev' || github.event.pull_request.base.ref == 'dev'
        uses: jeffDevelops/late-stage/.github/workflows/DevPR.yml@dev # <- TODO: Change branch to main

      - name: Check if pull request -> staging
        if: github.event.pull_request.base.ref == 'staging'
        run: echo "Running staging branch PR workflow"
        
      - name: Check if pull request -> main
        if: github.event.pull_request.base.ref == 'main'
        run: echo "Running main branch PR workflow"
