name: PR
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - staging
  workflow_dispatch:
jobs:
  check-if-dev-branch:
    if: github.ref == 'refs/heads/dev' || github.event.pull_request.base.ref == 'dev'
    uses: jeffDevelops/late-stage/.github/workflows/DevPR.yml@dev # <- TODO: Change branch to main
    environment: dev
    secrets:
      # API
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      STAGING_DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}

      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}

      STAGING_DATABASE_USER: ${{ secrets.STAGING_DATABASE_USER }}
      STAGING_DATABASE_PASSWORD: ${{ secrets.STAGING_DATABASE_PASSWORD }}
      STAGING_DATABASE_HOST: ${{ secrets.STAGING_DATABASE_HOST }}
      STAGING_DATABASE_PORT: ${{ secrets.STAGING_DATABASE_PORT }}
      STAGING_DATABASE_NAME: ${{ secrets.STAGING_DATABASE_NAME }}

      API_KEY: ${{ secrets.API_KEY }}
      COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

      # Client
      VITE_SVELTEKIT_HOST: ${{ secrets.VITE_SVELTEKIT_HOST }}
      VITE_HOST_ADDRESS: ${{ secrets.VITE_HOST_ADDRESS }}
      API_HOST: ${{ secrets.API_HOST }}
      API_PATH: ${{ secrets.API_PATH }}

  check-if-staging-branch:
    if: github.event.pull_request.base.ref == 'staging'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Check if pull request -> staging
        run: echo "Running staging branch PR workflow"

  check-if-main-branch:
    if: github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check if pull request -> main
        run: echo "Running main branch PR workflow"
